### ISSUE TITLE
Quill dependency not found

### ISSUE THREAD

**Issue by Arthav24** [bekirbostanci/vda5050_visualizer#2]
getting this error 
  ➜  Local:   http://localhost:8080/
  ➜  Network: http://192.168.17.213:8080/
  ➜  Network: http://172.18.0.1:8080/
✘ [ERROR] Could not resolve "Quill"

    node_modules/balm-ui/dist/balm-ui-plus.js:1:107:
      1 │ ...bject"===typeof exports&&"object"===typeof module?module.exports=t(require("vue"),require("Quill")):"function"===typeof define&&define.amd?define("BalmUIPlus",["vue","Quill"],t):"object"=...
        ╵                                                                                              ~~~~~~~

  You can mark the path "Quill" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

tried installing quill and ngx-quill but didnt work. Also the docker file has same issue

**Comment by bekirbostanci** [comment]
I tried 2 different computer to run it and at first time it worked. What is the main difference I am not sure. Also which operating system are you using?

**Comment by Arthav24** [comment]
I am trying on ubuntu 20.04. Tried dockerized version too on node:14

**Comment by bekirbostanci** [comment]
Did you try production version ? Does it have same problem ?

**Comment by nv-yuzho** [comment]
The dev docker file has the same Quill missing error.
The prod docker file shows the below output but the page is blank.
```
> vda_visualizer@0.0.0 preview /app
> vite preview --host

  ➜  Local:   http://localhost:4173/
  ➜  Network: http://192.168.222.2:4173/
```
I'm also using Ubuntu 20.04.

**Comment by bekirbostanci** [comment]
Sorry I want to solve the problem and help to you but I can not reproduce the problem in my computer so that it is not really easy to solve. However if you have time we can schedule a meeting and solve problem in your computer. bekirbostanci@gmail.com my email. You can send an email to me and we can solve it in your computer.

**Comment by bekirbostanci** [comment]
The problem solved with removing balm ui plus 
https://github.com/bekirbostanci/vda5050_visualizer/commit/ff04f6e0b165d9921f8e13b359cd530403a7d5a8
